backend/models/Company.php
<?php

namespace backend\models;

use Yii;


/**
 * This is the model class for table "{{%tv_company}}".
 *
 * @property integer $id
 * @property string $name
 * @property string $adress
 * @property string $phone
 * @property integer $node_count
 * @property integer $cma_count
 */
class Company extends BaseModel
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%tv_company}}';
    }

    /**
     * 返回一个该model的缓存文件的前缀
     * @return string
     * @static
     * $appKeyPrefix.$modelPrefix.$id
     */
    public static function cacheKey()
    {
        return 'company_cache:';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'adress', 'phone'], 'required','message'=>'不能为空'],
            ['name', 'match','pattern'=>'/^[(\x{4E00}-\x{9FA5})a-zA-Z]+[(\x{4E00}-\x{9FA5})a-zA-Z_\d]*$/u','message'=>'单位名称由字母，汉字，数字，下划线组成，且不能以数字和下划线开头。'],
            ['adress', 'match','pattern'=>'/^[(\x{4E00}-\x{9FA5})a-zA-Z]+[(\x{4E00}-\x{9FA5})a-zA-Z_\d]*$/u','message'=>'单位地址由字母，汉字，数字，下划线组成，且不能以数字和下划线开头。'],
            // ['name','required','message'=>'公司名称不能为空'],
            // ['phone','required','message'=>'电话号码不能为空'],
            [['node_count', 'cma_count'], 'integer'],
            [['name', 'adress'], 'string', 'max' => 255],
            //正则验证
            ['phone', 'match','pattern'=>'/(^(86)\-(0\d{2,3})\-(\d{7,8})\-(\d{1,4})$)|(^0(\d{2,3})\-(\d{7,8})$)|(^0(\d{2,3})\-(\d{7,8})\-(\d{1,4})$)|(^(86)\-(\d{3,4})\-(\d{7,8})$)/','message'=>'电话号码格式不正确'],
            //自定义验证
            [['node_count'], 'check_count'],

            // 检查 "level" 是否为 1、2 或 3 中的一个
            //['level', 'in', 'range' => [1, 2, 3]],

            // 检查 "username" 是否为长度 4 到 24 之间的字符串
            //['username', 'string', 'length' => [4, 24]],
        ];
    }

    //自定义验证
    public function check_count(){
        if($this->node_count < 0){
            $this->addError('node_count','node_count不能小于0');
        }
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('common','Company Id'),
            'name' => Yii::t('common','Company Name'),  //单位名称
            'adress' => Yii::t('common','Company Address'),
            'phone' => Yii::t('common','Company Phone'),
            'node_count' => Yii::t('common','Company Node Count'),
            'cma_count' => Yii::t('common','Company Camera Count'),
        ];
    }

    /*
    * Set AllCompany Redis
    */
    public function setAllRedis(){
        $com_id = Yii::$app->cache->redis->INCR($this->id);   //add 1
        Yii::$app->cache->redis->hmset('company:'.$com_id,    //'com:'.$this->id,Redis的哈希键值对的集合，对于Redis命令 com:1 是键
            [
                'id'=>$this->id,
                'name'=>$this->name,
                'adress'=>$this->adress,
                'phone'=>$this->phone,
                'node_cout'=>$this->node_count,
                'cma_count'=>$this->cma_count
            ]
        );
    }

    /*
    * Set Company Redis
    */
    public function setCompanyRedis(){
        Yii::$app->cache->redis->set('time',time());        //保存该单位最后修改的时间信息
        Yii::$app->cache->redis->hmset('company:'.$this->id,    //'com:'.$this->id,Redis的哈希键值对的集合，对于Redis命令 com:1 是键
            'id',$this->id,
            'name',$this->name,
            'adress',$this->adress,
            'phone',$this->phone,
            'node_cout',$this->node_count,
            'cma_count',$this->cma_count
        );
    }

    /*
     * Get Company Redis
     */
    public function getCompanytRedis($id){
        $redis_arr = [];
        $redis_arr['id'] = Yii::$app->cache->redis->HGET('company:'.$id,'id');
        $redis_arr['name'] = Yii::$app->cache->redis->HGET('company:'.$id,'name');
        $redis_arr['adress'] = Yii::$app->cache->redis->HGET('company:'.$id,'adress');
        $redis_arr['phone'] = Yii::$app->cache->redis->HGET('company:'.$id,'phone');
        $redis_arr['node_count'] = Yii::$app->cache->redis->HGET('company:'.$id,'node_count');
        $redis_arr['cma_count'] = Yii::$app->cache->redis->HGET('company:'.$id,'cma_count');
        return $redis_arr;
    }

    /*
     * Delete Company Redis
     */
    public function delCompanyRedis(){
        Yii::$app->cache->redis->del('time');
        Yii::$app->cache->redis->del('company:'.$this->id);
    }
}

backend/controllers/CompanyController.php
<?php

namespace backend\controllers;

use backend\models\Times;
use backend\models\CamSet;
use backend\models\Camera;
use backend\models\Node;
use Yii;
use backend\models\search\CompanySearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\data\Pagination;
use backend\models\Company;

/**
 * CompanyController implements the CRUD actions for Company model.
 */
class CompanyController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    // 缓存一条记录
    public function actionRedisHtml($id = 0)
    {
        if($id){
            // Model的静态方法，cacheKey()返回一个该Model缓存的一个缓存前缀
            // eg: $appKeyPrefix.$modelPrefix.$id 使用逻辑删除1
            $key = Company::cacheKey().$id;

            $model = \Yii::$app->cache->get($key);
            // 如果缓存不存在
            if($model === false){
                $model = Company::findOne($id);
                /**
                 * set($key, $value, $duration = 0, $dependency = null)
                 *  添加缓存
                 */
                \Yii::$app->cache->set($key,$model);
            }
            $model->views++;
            $model->save();
            return $this->render('new_detail',[
                'model'=>$model,
            ]);
        }
    }

    /**
     * 在这里只要指定这个类就可以了 'class' => 'yii\web\ErrorAction',
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Lists all Company models.
     * @return mixed
     */
    public function actionIndex()
    {
        $model = new Company();
        $model->scenario = 'login';

        $curPage = Yii::$app->request->get('page',1);
        $pageSize = 14;

        $name = Yii::$app->request->get('name','');
        $address = Yii::$app->request->get('address','');

        $search = ($name&&$address)?['like',$name,$address]:'';
        //
        $query = $model->find()->orderBy('id DESC');
        $data = $model->getPages($query,$curPage,$pageSize,$search);
        $pages = new Pagination([
            'totalCount' =>$data[ 'count'],
            'pageSize' => $pageSize,
            //默认带的有每页的数量per-page 如果你不想显示该参数，设置pageSizeParam=false就好
            'pageSizeParam' => false,
            //默认的页面取决于参数page,如果你想改变该参数为p,设置pageParam=p就好
            'pageParam' => 'p',
            //如果你的分页存在于首页，相信你肯定想要/?p=1而不是/site/index?p=1，我们看看怎么隐藏掉路由
            'route' => false,
            //可能你会发现分页类Pagination有一个bug,假如我们只有1页的数据，但是手动更改地址栏的page=20的时候，也会显示page=1的数据？当然，这在大部分接口API中就很让人厌烦。但是，这并非bug,而是一种友好的验证。设置validatePage=false即可避免掉该问题
            'validatePage' => false,
        ]);
        return $this->render('index',[
            'pages'=>$pages,
            'data'=>$data
        ]);
    }

    /**
     * Displays a single Company model.
     * @param integer $id
     * @return mixed
     */
    //    public function actionDao($id){
    //        $company_arr = Company::find()->where('id = :id',[':id'=>$id])->asArray()->one();
    //        $camera_arr  = Camera::find()->where('id = :id',[':id'=>$id])->asArray()->one();
    //        var_dump($camera_arr);
    //    }

    /**
     * Displays a single Company model.
     * @param integer $id
     * @return mixed
     */
    //    public function actionView($id)
    //    {
    //        return $this->render('view', [
    //            'model' => $this->findModel($id),
    //        ]);
    //    }

    /**
     * this is result Success
     */
    public function actionCreate()
    {
        // 新建一条记录
        $model = new Company();
        // 获取用户输入的数据，验证并保存
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $model->setCompanyRedis();
            return $this->redirect(['index']);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Company model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    //    public function actionUpdate($id)
    //    {
    //        $model = $this->findModel($id);
    //
    //        if ($model->load(Yii::$app->request->post()) && $model->save()) {
    //            return $this->redirect(['view', 'id' => $model->id]);
    //        } else {
    //            return $this->render('update', [
    //                'model' => $model,
    //            ]);
    //        }
    //    }

    /**
     * Deletes an existing Company model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        /*
         *  @循环遍历删除
         *  1.先查找单位下-->摄像头是否存在--->摄像头是否已经设置
         *  2.在查找节点以及节点的时间段设置
         *  3.删除单位信息
        */

        //查找所有的节点
        $node_model = Node::find()->where('com_id = :com_id')->addParams([':com_id'=>$id])->all();
        foreach($node_model as $nodes){
            //查找节点设置
           $node_set = Times::find()->where('node_id = :node_id')->addParams([':node_id'=>$nodes->id])->all();
           foreach($node_set as $set){
               $set->delTimesRedis($nodes->id);
               $set->delete();
           }
           $nodes->delNodeRedis($nodes->com_id);
           $nodes->delete();
        }

        //查找所有的摄像头
        $camera_model = Camera::find()->where('com_id = :com_id',[':com_id'=>$id])->all();
        foreach($camera_model as $cameras){
            //查找摄像头设置
            $camera_set = CamSet::find()->where('cam_id = :cam_id')->addParams([':cam_id'=>$cameras->id])->all();
            foreach($camera_set as $sets){
                $sets->delRedis($cameras->id);
                $sets->delete();
            }
            $cameras->delCameraRedis($cameras->node_id);
            $cameras->delete();
        }

        //单位信息
        $this->findModel($id)->delCompanyRedis();
        $this->findModel($id)->delete();

        /**
         * 使用逻辑删除，实际是没有删除的
         */
        $model = $this->findModel($id);
        $model->status = 1;
        $model->save();

        /**
         * 删除对应的缓存信息
         */
        $key = Company::cacheKey().$id;
        Yii::$app->cache->delete($key);

        return $this->redirect(['index']);
    }

    /**
     * Finds the Company model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Company the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Company::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('这请求页是不存在.');
        }
    }

    /**
     * Test Redis
     */
    public function actionTest(){
//        Yii::$app->redis->set('test','111123');     //设置redis缓存
        echo Yii::$app->cache->redis->get('cid64');         //获取redis缓存
//        Yii::$app->cache->set('rediscache','110112');
//        $model = new Company();
//        $model->getRedis();
//        echo 111;
        exit();
    }

    /**
     * 编辑单位
     */
    public function actionEdit($id){
        $company = Company::find()->where('id = :id',[':id'=>$id])->asArray()->one();
        $camera  = Camera::find()->where('com_id = :com_id',[':com_id'=>$id])->asArray()->All();
        $nodes   = Node::find()->where('com_id = :com_id',[':com_id'=>$id])->asArray()->All();
        return $this->render('edit',[
            'companys' => $company,
            'nodes'   => $nodes,
            'cameras'  => $camera
        ]);
    }

    public function actionRedis(){
        $model = new Company();
        $redis = $model->getRedis('70');
        var_dump($redis);
        die();
    }

    public function actionMailer(){
        $result = Yii::$app->mailer->compose()
            ->setFrom('1722318623@qq.com')
            ->setTo('756684177@qq.com')
            ->setSubject('Message subject')
            ->setTextBody('Plain text content')
            ->setHtmlBody('<b>HTML content</b>')
            ->send();
        $sms = Yii::$app->smser->send('13669361192','000000');
    }

}

frontend/controllers/CompanyController.php
<?php

namespace frontend\controllers;

use backend\models\Camera;
use backend\models\CamSet;
use backend\models\Node;
use backend\models\Times;
use frontend\models\LoginUserForm;
use Yii;
use yii\data\ActiveDataProvider;
use yii\helpers\Console;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

use backend\models\Company;

/**
 * CompanyController implements the CRUD actions for Company model.
 */
class CompanyController extends Controller
{
    const TIME = '';
    const RRR = '';
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Company models.
     * @return mixed
     */
    public function actionIndex($id)
    {
        //单位信息
        $com_model = new Company();
        $company_redis = $com_model->getCompanytRedis($id);

        //获取所有的节点信息
        $node_model = new Node();
        $node_redis = $node_model->getAllRedis($id);

        //$nodes = $node_model->find()->where('com_id = :com_id',[':com_id'=>$id])->all();
        $nodes = $node_model->find()->where('com_id = :com_id')->addParams([':com_id'=>$id])->all();

        foreach($nodes as $node){
            $node_arr[] = $node->id;
        }
        //获取节点设置时段信息
        if(isset($node_arr)){
            $time_model = new Times();
            $time_redis = $time_model->getAllRedis($node_arr);
        }else{
            $time_redis = [];
        }
        //获取所有的摄像头信息
        if(isset($node_arr)){
            $camera_model = new Camera();
            $camera_redis = $camera_model->getAllRedis($node_arr);  //这里传递的是一个数组
        }else{
            $camera_redis = [];
        }

        if(isset($camera_redis)){
            //获取的摄像头设置信息
            $camset_model = new CamSet();
            foreach($camera_redis as $cam){
                $cam_arr[] = $cam['id'];
            }
            if(isset($cam_arr)){
                $camset_redis = $camset_model->getAllRedis($cam_arr);
            }else{
                $camset_redis = [];
            }
        }else{
            $camset_redis = [];
        }
        //获取时间
        $time_info = Yii::$app->cache->redis->get('time');

        //保存信息到数组中
        $redis_arr = [
            'time' => $time_info,
            'company' => $company_redis,
            'node' => $node_redis,
            'camera' => $camera_redis,
            'node_times' => $time_redis,
            'camera_set' => $camset_redis
        ];
        //转换为json保存在本地
        $RootDir = Yii::$app->BasePath;
        $FilePath = "$RootDir/data/data.txt";
        file_put_contents($FilePath,json_encode($redis_arr));
        //$array = [1,2,3,4,5,5,5,5];
        return $this->render('main',[
            'company' => $company_redis,
        ]);
    }

    //登录判断
    public function actionLogin()
    {
        $this->layout = 'login';
        $model = new LoginUserForm();

        if ($model->load(Yii::$app->request->post())) {
            //LoginUser模型中判断当前单位信息的redis是否存在
            if($model->checkRedis()){
                Yii::$app->params['redis_host'] = $model->redis_host;
                return $this->redirect(['index', 'id' => $model->id]);
            }else{
                return $this->render('error');
            }
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionTest(){
        $model = Yii::$app->cache->redis->EXISTS('company:98'); //获取到的是一个数组
        if(empty($model)){
            return false;
        }
        return true;

        //echo $model[1];
    }

    public function actionJson(){
        $basePath = Yii::$app->basePath;
        $filePath = $basePath.'/data/data.txt';
        $fileJosn = file_get_contents($filePath);
        var_dump(json_decode($fileJosn));
        echo $filePath;
    }
}

backend/views/company/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\redactor\widgets\Redactor;

/* @var $this yii\web\View */
/* @var $model app\models\Company */
/* @var $form yii\widgets\ActiveForm */
?>


<div class="company-form">

    <?php $form = ActiveForm::begin([
        'id' => 'msg-form',
        'options' => ['class'=>'form-horizontal'],
        'enableAjaxValidation'=>false,
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ]
    ]);
    ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>


    <?= $form->field($model, 'phone')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'adress')->widget(Redactor::className(), [
        'clientOptions' => [
            'imageManagerJson' => ['/redactor/upload/image-json'],
            'imageUpload' => ['/redactor/upload/image'],
            'fileUpload' => ['/redactor/upload/file'],
            'lang' => 'zh_cn',
            'plugins' => ['clips', 'fontcolor','imagemanager']
        ]
    ])?>

    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-11">
          <?= Html::submitButton($model->isNewRecord ? '创建' : '修改', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/company/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\search\CompanySearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="company-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'adress') ?>

    <?= $form->field($model, 'phone') ?>

    <?= $form->field($model, 'node_count') ?>

    <?php // echo $form->field($model, 'cma_count') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/company/create - 副本.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Company */

$this->title = Yii::t('common','Company List');
$this->params['breadcrumbs'][] = ['label' => 'Companies', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="company-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/company/create.php
<?php

use yii\helpers\Html;
use \yii\widgets\ActiveForm;


/* @var $this yii\web\View */
/* @var $model app\models\Company */

$this->title = '添加新单位';
$this->params['breadcrumbs'][] = ['label' => 'Companies', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="company-create">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/company/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The is Company Error Page
    </p>

</div>

backend/views/company/index - 副本.php
<?php

use yii\helpers\Html;
use backend\models\LinkPages;
use yii\widgets;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\CompanySearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('common','Company List');
$this->params['breadcrumbs'][] = $this->title;
?>
<div id="content" class="white">
    <h1>
    </h1>
    <div class="bloc">
        <div class="title">
            单位信息
        </div>
        <div class="content">
            <table>
                <thead>
                <tr>
                    <th><input type="checkbox" class="checkall"/></th>
                    <th>ID</th>
                    <th>单位名称</th>
                    <th>地址</th>
                    <th>联系电话</th>
                    <th>节点数</th>
                    <th>摄像头数</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                <?php
                    foreach($data['data'] as $company):
                ?>

                    <tr>
                        <td><?=Html::encode($company['id'])?></td>
                        <td><?=Html::encode($company['id'])?></td>
                        <td><?=Html::encode($company['name'])?></td>
                        <td><?=Html::encode($company['adress'])?></td>
                        <td><?=Html::encode($company['phone'])?></td>
                        <td><?=Html::encode($company['node_count'])?></td>
                        <td><?=Html::encode($company['cma_count'])?></td>
                        <td>
                            <a href="<?=Yii::$app->urlManager->createUrl(['company/dao','id'=>$company['id']]);?>" class="handle-btn edit-btn">编辑</a>
                            <a href="<?=Yii::$app->urlManager->createUrl(['company/delete','id'=>$company['id']]);?>" class="handle-btn del-btn">删除</a>
                        </td>
                    </tr>
                <?php
                    endforeach;
                ?>
                </volist>
                </tbody>
            </table>
            <div style="clear: both;">
                <?=LinkPages:: widget([
                    'pagination' => $pages,
                    'maxButtonCount' => 6,  //显示分页数量,默认的就是10个哦
                    'firstPageLabel' => '首页',
                    'nextPageLabel' => '下一页',
                    'prevPageLabel' => '上一页',
                    'lastPageLabel' => '尾页',
                ]);?>
            </div>

        </div>
    </div>
</div>

backend/views/company/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use backend\models\LinkPages;
use yii\widgets;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\CompanySearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('common','Company List');
$this->params['breadcrumbs'][] = ['label'=>Yii::t('common','Company Manage'),'url'=>'index'];
$this->params['breadcrumbs'][] = ['label'=>$this->title];
?>

<!-- DATA TABLES -->
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h2><i class="fa fa-table red"></i><span class="break"></span><strong>单位信息列表</strong></h2>
                <div class="panel-actions">
                    <a href="table.html#" class="btn-setting"><i class="fa fa-rotate-right"></i></a>
                    <a href="table.html#" class="btn-minimize"><i class="fa fa-chevron-up"></i></a>
                    <a href="table.html#" class="btn-close"><i class="fa fa-times"></i></a>
                </div>
            </div>
            <div class="panel-body">
                <table class="table table-bordered table-striped table-condensed table-hover">
                    <thead>
                    <tr>
                        <th>序号</th>
                        <th>#ID</th>
                        <th>单位名称</th>
                        <th>地址</th>
                        <th>联系电话</th>
                        <th>节点数</th>
                        <th>摄像头数</th>
                        <th>
                          <?=Html::a("新增单位 <i class='icon-plus'></i>" , ['company/create' ], ['class' => 'btn btn-success btn-sm']) ?>
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php
                    $i = 1;
                    foreach ($data['data'] as $company):
                        ?>
                        <tr>
                            <td><?=Html::encode($i); ?></td>
                            <td><?=Html::encode($company['id']); ?></td>
                            <td><?=Html::encode($company['name']); ?></td>
                            <td><?=Html::encode($company['adress']); ?></td>
                            <td><?=Html::encode($company['phone']); ?></td>
                            <td><?=Html::encode($company['node_count']); ?></td>
                            <td><?=Html::encode($company['cma_count']); ?></td>
                            <td>
                                <a class="btn btn-primary btn-sm" 
                                href="<?=Url::to(['company/edit','id'=>$company['id']])?>" data-method="post">编辑</a>
                                <a class="btn btn-danger btn-sm" 
                                href="<?=Url::to(['company/delete','id'=>$company['id']])?>" data-method="post" data-confirm="您确定要删除此项吗？">删除</a>
                            </td>
                        </tr>
                        <?php
                        $i++;
                    endforeach;
                    ?>

                    </tbody>
                </table>
                <?=LinkPages:: widget([
                    'pagination' => $pages,
                    'maxButtonCount' => 6,  //显示分页数量,默认的就是10个哦
                    'firstPageLabel' => '首页',
                    'nextPageLabel' => '下一页',
                    'prevPageLabel' => '上一页',
                    'lastPageLabel' => '尾页',
                    //如果你的数据过少，不够2页，默认不显示分页，如果你需要，设置
                    'hideOnSinglePage' => false,
                    //'options' => ['class' => 'm-pagination'], //自己写的样式
                ]);?>
            </div>
        </div>
    </div><!--/col-->
</div><!--/row-->

backend/views/company/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Company */

$this->title = 'Update Company: ' . ' ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Companies', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="company-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/company/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Company */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Companies', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="company-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            'adress',
            'phone',
            'node_count',
            'cma_count',
        ],
    ]) ?>

</div>