backend/models/Times.php
<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "{{%tv_times}}".
 *
 * @property integer $id
 * @property integer $node_id
 * @property string $star_time
 * @property string $end_time
 */
class Times extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%tv_times}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['star_time', 'end_time'], 'required'],
            [['star_time', 'end_time'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'node_id' => '节点ID',
            'star_time' => '开始时间',
            'end_time' => '结束时间',
        ];
    }

    /*
   * Set Times Redis
   */
    public function setTimesRedis(){
        Yii::$app->cache->redis->set('time', time()); //节点最后修改的时间信息
        Yii::$app->cache->redis->hmset(
            'node'.$this->node_id.':times'.$this->id,
            'id',$this->id,
            'node_id',$this->node_id,
            'star_time',$this->star_time,
            'end_time',$this->end_time
        );
    }

    /*
     * Get Times Redis
     */
    public function getTimesRedis($id){
        $redis_arr = [];
        $redis_arr['id'] = Yii::$app->cache->redis->HGET('company:'.$id,'id');
        $redis_arr['name'] = Yii::$app->cache->redis->HGET('company:'.$id,'name');
        $redis_arr['adress'] = Yii::$app->cache->redis->HGET('company:'.$id,'adress');
        $redis_arr['phone'] = Yii::$app->cache->redis->HGET('company:'.$id,'phone');
        $redis_arr['node_count'] = Yii::$app->cache->redis->HGET('company:'.$id,'node_count');
        $redis_arr['cma_count'] = Yii::$app->cache->redis->HGET('company:'.$id,'cma_count');
        return $redis_arr;
    }

    /*
     * Delete Times Redis
     */
    public function delTimesRedis($id){
        Yii::$app->cache->redis->del('time');
        Yii::$app->cache->redis->del('node'.$id.':times'.$this->id);
    }

    /*
     * Get All Times Redis
     */
    public function getAllRedis($node_arr){
        foreach($node_arr as $node_id){
            foreach(Yii::$app->cache->redis->KEYS('node'.$node_id.':times*') as $times){
                $time_arr[] = [
                    'id'         => Yii::$app->cache->redis->HGET($times,'id'),
                    'node_id'    => Yii::$app->cache->redis->HGET($times,'node_id'),
                    'star_time'  => Yii::$app->cache->redis->HGET($times,'star_time'),
                    'end_time'   => Yii::$app->cache->redis->HGET($times,'end_time')
                ];
            }
        }
        return $time_arr;
    }
}

backend/controllers/TimesController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\Times;
use backend\models\Node;
use backend\models\search\TimesSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * TimesController implements the CRUD actions for Times model.
 */
class TimesController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Times models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new TimesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Times model.
     * @param integer $id
     * @return mixed
     */
    //    public function actionView($id)
    //    {
    //        return $this->render('view', [
    //            'model' => $this->findModel($id),
    //        ]);
    //    }

    /**
     * Creates a new Times model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($node_id)
    {
        $model = new Times();
        $com_id = Node::findOne(['id'=>$node_id])->com_id;
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $model->node_id = $node_id;
            $model->save();
            $model->setTimesRedis();
            return $this->redirect(['times/set','node_id'=>$node_id]);
        } else {
            return $this->render('create', [
                'model' => $model,
                'com_id' => $com_id,
                'node_id' => $node_id
            ]);
        }
    }

    /**
     * Updates an existing Times model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $com_id = Node::findOne(['id'=>$model->node_id])->com_id;
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $model->setTimesRedis();
            return $this->redirect(['set', 'node_id' => $model->node_id]);
        } else {
            return $this->render('update', [
                'model' => $model,
                'com_id' => $com_id,
                'node_id' => $model->node_id
            ]);
        }
    }

    /**
     * Deletes an existing Times model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Times model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Times the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Times::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     * 节点时间段设置
     */
    public function actionSet($node_id){
        $model = Times::find()->where('node_id = :node_id',[':node_id'=>$node_id])->asArray()->all();
        $n_model = Node::findOne(['id'=>$node_id]);
        return $this->render('index',[
            'node_id' =>$node_id,
            'com_id'      =>$n_model->com_id,
            'times'   =>$model,
        ]);
    }
}

backend/views/times/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\Times */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="times-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'star_time')->textInput() ?>

    <?= $form->field($model, 'end_time')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? '确认' : '修改', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/times/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\search\TimesSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="times-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'node_id') ?>

    <?= $form->field($model, 'star_time') ?>

    <?= $form->field($model, 'end_time') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/times/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model backend\models\Times */

$this->title = Yii::t('common','Create Times');
$this->params['breadcrumbs'][] = ['label'=>Yii::t('common','Company Manage'),'url'=>'/company/index'];
$this->params['breadcrumbs'][] = ['label'=>Yii::t('common','Company Set'),'url'=>['/company/edit','id'=>$com_id]];
$this->params['breadcrumbs'][] = ['label'=>Yii::t('common','Times Manage'),'url'=>['/times/set','node_id'=>$node_id]];
$this->params['breadcrumbs'][] = ['label' => $this->title];
?>
<div class="times-create">

    <?= $this->render('_form', [
        'model' => $model,
        ''
    ]) ?>

</div>

backend/views/times/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\search\TimesSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('common','Times Manage');
$this->params['breadcrumbs'][] = ['label'=>Yii::t('common','Company Manage'),'url'=>'/company/index'];
$this->params['breadcrumbs'][] = ['label'=>Yii::t('common','Company Set'),'url'=>['/company/edit','id'=>$com_id]];
$this->params['breadcrumbs'][] = $this->title;
?>
<!-- DATA TABLES -->
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h2><i class="fa fa-table red"></i><span class="break"></span><strong>节点时间设置列表</strong></h2>
                <div class="panel-actions">
                    <a href="table.html#" class="btn-setting"><i class="fa fa-rotate-right"></i></a>
                    <a href="table.html#" class="btn-minimize"><i class="fa fa-chevron-up"></i></a>
                    <a href="table.html#" class="btn-close"><i class="fa fa-times"></i></a>
                </div>
            </div>
            <div class="panel-body">
                <table class="table table-bordered table-striped table-condensed table-hover">
                    <thead>
                    <tr>
                        <th>序号</th>
                        <th>#ID</th>
                        <th>节点信息</th>
                        <th>开始时间</th>
                        <th>结束时间</th>
                        <th>
                            <a class="btn btn-primary btn-sm"
                               href="<?=Url::to(['times/create','node_id'=>$node_id])?>" data-method="post">新增时间段</a>
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php
                    $i = 1;
                    foreach ($times as $time):
                        ?>
                        <tr>
                            <td><?=Html::encode($i); ?></td>
                            <td><?=Html::encode($time['id']); ?></td>
                            <td><?=Html::encode($time['node_id']); ?></td>
                            <td><?=Html::encode($time['star_time']); ?></td>
                            <td><?=Html::encode($time['end_time']); ?></td>
                            <td>
                                <a class="btn btn-primary btn-sm"
                                   href="<?=Url::to(['times/update','id'=>$time['id']])?>" data-method="post">编辑</a>
                                <a class="btn btn-danger btn-sm"
                                   href="<?=Url::to(['times/delete','id'=>$time['id']])?>" data-method="post" data-confirm="您确定要删除此项吗？">删除</a>
                            </td>
                        </tr>
                        <?php
                        $i++;
                    endforeach;
                    ?>

                    </tbody>
                </table>
            </div>
        </div>
    </div><!--/col-->
</div><!--/row-->

backend/views/times/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\Times */

$this->title = Yii::t('common','Update Times');
$this->params['breadcrumbs'][] = ['label'=>Yii::t('common','Company Manage'),'url'=>'/company/index'];
$this->params['breadcrumbs'][] = ['label'=>Yii::t('common','Company Set'),'url'=>['/company/edit','id'=>$com_id]];
$this->params['breadcrumbs'][] = ['label'=>Yii::t('common','Times Manage'),'url'=>['/times/set','node_id'=>$node_id]];
$this->params['breadcrumbs'][] = ['label' => $this->title];
?>
<div class="times-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/times/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model backend\models\Times */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Times', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="times-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'node_id',
            'star_time',
            'end_time',
        ],
    ]) ?>

</div>